import Head from "next/head";
import Router from "next/router";
import * as S from "../styles/style";

export default function Landing() {
  setTimeout(() => {
    Router.push("/auth");
  }, 3000);
  return (
    <>
      <Head>
        <title>Havit, Have it!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <S.Main>
        <img src="../Landing.gif" />
      </S.Main>
    </>
  );
}
